### ISSUE TITLE
cfg not applied on viewer

### ISSUE THREAD

**Issue by cyrilbele** [bimdata/documentation#121]
I ran the viewer available at this page
https://developers.bimdata.io/tutorials/using_custom_viewer.html

but all the components are displayed even with everything set to false

**Comment by Amoki** [comment]
Oops, this page is a bit out of date.
To disable components, you now have to use an object named `bimdataPlugins`
```js
      const cfg = {
        cloudId: 88,
        projectId: 100,
        ifcIds: [175],
        bimdataPlugins: {
          bcf: false
        }
      }
```
This page have to correct syntax: https://developers.bimdata.io/viewer/index.html
