### ISSUE TITLE
Documentation-modifier champs de recherche

### ISSUE THREAD

**Issue by GabBimdata** [bimdata/documentation#4]
![image](https://user-images.githubusercontent.com/32667664/48936075-08bb3c80-ef0a-11e8-9e6e-35b57b354128.png)
![image](https://user-images.githubusercontent.com/32667664/48936081-0ce75a00-ef0a-11e8-91fb-a28242f20dac.png)

J'ai mumuse avec le css pour rendre le tout un peu plus joli. Possible de : 
- changer le border radius en 3px
- mettre la couleur : #8E97AE en border color

**Comment by mere-teresa** [comment]
Voir la PR
