### ISSUE TITLE
staging: reference does not exists (getRawelements)

### ISSUE THREAD

**Issue by allankicker** [bimdata/documentation#48]
Doc mention to refer to `getRawElements` (image below) but this reference does not exists in the doc, i think it refers to `/element/raw`

![image](https://user-images.githubusercontent.com/25752207/57931456-cc650980-78b8-11e9-85fb-12745da44c4f.png)

**Comment by mere-teresa** [comment]
Additional info: the URL is https://developers-staging.bimdata.io/api/index.html#operation--cloud--cloud_pk--project--project_pk--ifc--ifc_pk--element-get

The text is written in the OpenAPI file, so...your side, Backend Team!

**Comment by Amoki** [comment]
It refers to the name of the endpoint (https://api-staging.bimdata.io/doc#/ifc/getRawElements) that exists
