### ISSUE TITLE
Documentation-modifier couleur du "+" dans la sidebar 

### ISSUE THREAD

**Issue by GabBimdata** [bimdata/documentation#5]
![image](https://user-images.githubusercontent.com/32667664/48936205-87b07500-ef0a-11e8-8060-f7dc2c8c52ad.png)
![image](https://user-images.githubusercontent.com/32667664/48936206-8b43fc00-ef0a-11e8-9ff3-19ec30f6fbbb.png)

Afin d'éviter du ton sur ton, serait-il possible de changer la couleur du "+" par du blanc ?

**Comment by mere-teresa** [comment]
Done !
