### ISSUE TITLE
Interface - comportement breadcrumb dans cookbook

### ISSUE THREAD

**Issue by GabBimdata** [bimdata/documentation#57]
![image](https://user-images.githubusercontent.com/32667664/59260268-973fa300-8c3b-11e9-9703-99ddb6eadab2.png)

Je suis allé voir un peu partout pour tester le darkmode et par réflexe j'ai voulu utiliser le breadcrumb pour retourner à la page principale du cookbook. Le truc c'est que c'est impossible lorsque nous sommes dans "Create a backend-less application" et "Create a backend application" nous n'avons plus accès à "cookbook".

**Comment by LrxGaelle** [comment]
Hum.. De ce que je vois, ça serait plutôt un "problème" de gestion et/ou d'appel des pages ? @mere-teresa
