### ISSUE TITLE
Documentation - Pas de description pour "filters" ? 

### ISSUE THREAD

**Issue by GabBimdata** [bimdata/documentation#58]
![image](https://user-images.githubusercontent.com/32667664/59260524-0b7a4680-8c3c-11e9-9e29-b64288046f94.png)

c'est curieux de ne pas avoir de description pour "filters" dans le guide. C'est un vrai choix de notre part de ne rien mettre ?

**Comment by mere-teresa** [comment]
Non ce n'est pas un choix, c'est un bug

**Comment by GabBimdata** [comment]
Je t'invites à déplacer l'issue dans "to validate" lorsqu'elle sera ok pour toi que je puisse tester tout ça. @mere-teresa
