### ISSUE TITLE
Interface - problème de style avec une admonition 

### ISSUE THREAD

**Issue by GabBimdata** [bimdata/documentation#60]
![image](https://user-images.githubusercontent.com/32667664/59260777-85123480-8c3c-11e9-8bbb-ada324f0c636.png)

![image](https://user-images.githubusercontent.com/32667664/59260889-bc80e100-8c3c-11e9-97f9-136552ad5074.png)

Je croyais que ça venait du darkmode mais en fait pas du tout. Je crois qu'on a un soucis avec une admonition dans la page "Create backend-less app" tout en bas. C'est un cas qu'on ne gère pas du tout ?

**Comment by LrxGaelle** [comment]
@GabBimdata, effectivement c'est une autre admonition. 
Actuellement on a "note", "warning" et "important". 
Et là c'est une admonition de type "tip"

**Comment by GabBimdata** [comment]
@LrxGaelle J'ai mis à jour les admonition TIP et j'ai ajouté l'admonition CAUTION à la demande de sarash. Tu trouveras ci-joint la version light moder et darkmode :) https://projects.invisionapp.com/d/main#/console/16405056/370829493/preview
https://projects.invisionapp.com/d/main#/console/16405056/370829494/preview

A noté également que j'ai (toujours à la demande de sarah) modifié l'admonition warning en transformant le rond en triangle. :)
