### ISSUE TITLE
Interface - animation doc api

### ISSUE THREAD

**Issue by GabBimdata** [bimdata/documentation#62]
Lorsque l'on clic dans le menu, l'animation est archi lente, je trouve qu'on met beaucoup trop de temps pour arriver à l'endroit ou on veut aller au débat. 

Il y a aussi un genre d'inertie au début de l'anim qui devient insupportable à force. 

Possible d'accélérer l'anim ? On peut faire des tests et voir ce qui est mieux. C'est même possible de ne pas mettre d'animation du tout.

**Comment by LrxGaelle** [comment]
@GabBimdata à vérifier avec @Amoki, mais j'ai l'impression qu'il a déjà fait ça de son côté ?

**Comment by GabBimdata** [comment]
Je vais aller voir ^^

**Comment by GabBimdata** [comment]
Sur staging j'ai toujours l'animation archi longue  @LrxGaelle
