### ISSUE TITLE
Title of admonition in the body of the admonition (instead of titlebar)

### ISSUE THREAD

**Issue by mere-teresa** [bimdata/documentation#78]
The title of the note, that RestructuredText format allows is not rendered by the current doc theme.

## In the RsT : 

```
.. note:: Title of the note
   
   Body of the note
```

## The output 

![note in dark mode: title not in title bar](https://user-images.githubusercontent.com/205895/62131316-42371980-b2db-11e9-92fc-da6b5d20b35a.png)

## HTML source code

```
<div class="admonition note">
<p class="first admonition-title">Note</p>
<p>Title of the note</p>
<p class="last">Body of the note</p>
</div>
```

### More info

http://docutils.sourceforge.net/docs/ref/doctree.html#admonition

**Comment by mere-teresa** [comment]
Branch : `semantic-links`

https://github.com/bimdata/documentation/blob/semantic-links/doc_sphinx/concepts/projects.rst

**Comment by LrxGaelle** [comment]
https://github.com/bimdata/documentation/commit/3a091e9f6ddb5acd5d352e576319587234109a8d
