### ISSUE TITLE
Documentation-retirer le picto "home" dans la sidebar

### ISSUE THREAD

**Issue by GabBimdata** [bimdata/documentation#9]
![image](https://user-images.githubusercontent.com/32667664/48936823-5d5fb700-ef0c-11e8-9f02-5f45f9320584.png)

Si on peut se passer de ce petit picto je signe pour tout de suite ! ^^

**Comment by mere-teresa** [comment]
PR #13

**Comment by mere-teresa** [comment]
Done !
